import { Broker, Property, PropertyFilters, PointOfInterest, Agency, Branch, Review } from "@/lib/types";

// Sdílené POI sady pro mock data
const poiPraha: PointOfInterest[] = [
  { name: "ZŠ a MŠ Střešovice", category: "school", distance: 350, walkMinutes: 5 },
  { name: "Metro A – Hradčanská", category: "transport", distance: 500, walkMinutes: 7 },
  { name: "Albert supermarket", category: "shop", distance: 200, walkMinutes: 3 },
  { name: "Restaurace U Cedru", category: "restaurant", distance: 300, walkMinutes: 4 },
  { name: "Stromovka", category: "park", distance: 800, walkMinutes: 10 },
  { name: "Nemocnice Na Bulovce", category: "health", distance: 1500, walkMinutes: 20 },
];

const poiBrno: PointOfInterest[] = [
  { name: "ZŠ Královodvorská", category: "school", distance: 400, walkMinutes: 5 },
  { name: "Tramvaj – Královo Pole", category: "transport", distance: 250, walkMinutes: 3 },
  { name: "Lidl", category: "shop", distance: 300, walkMinutes: 4 },
  { name: "Park Lužánky", category: "park", distance: 1200, walkMinutes: 15 },
  { name: "FN Brno", category: "health", distance: 900, walkMinutes: 12 },
  { name: "Sportovní centrum Riviera", category: "sport", distance: 1800, walkMinutes: 22 },
];

const poiMale: PointOfInterest[] = [
  { name: "ZŠ Náměstí Míru", category: "school", distance: 600, walkMinutes: 8 },
  { name: "Autobus – centrum", category: "transport", distance: 150, walkMinutes: 2 },
  { name: "Penny Market", category: "shop", distance: 400, walkMinutes: 5 },
  { name: "Městský park", category: "park", distance: 500, walkMinutes: 6 },
];

// ===== MOCK DATA – bude nahrazeno Supabase =====

// Krátké aliasy pro obrázky
const img = {
  vila1: "/images/u9534644866_A_luxurious_family_home_exterior_in_a_modern_arch_79afac09-b8fc-422f-8681-d24b4e78ec2c_1.png",
  vila2: "/images/u9534644866_A_hypermodern_luxury_house_with_futuristic_archit_038b2e37-1fbc-4d5b-a953-675705175b3a_2.png",
  vila3: "/images/u9534644866_A_hypermodern_luxury_house_with_futuristic_archit_038b2e37-1fbc-4d5b-a953-675705175b3a_3.png",
  vila4: "/images/u9534644866_A_luxurious_family_home_interior_and_exterior._In_09a4c657-005b-494c-a624-c9f226b06d83_0.png",
  vila5: "/images/u9534644866_A_luxurious_family_home_interior_and_exterior._In_09a4c657-005b-494c-a624-c9f226b06d83_3.png",
  dum1: "/images/u9534644866_A_modern_luxury_home_exterior_with_a_sleek_garage_807055a2-b1a6-486c-a56b-051b92561a75_0.png",
  dum2: "/images/u9534644866_A_modern_luxury_home_exterior_with_a_sleek_garage_487a76ef-f23e-4ea3-9d35-bba43fa61724_2.png",
  dum3: "/images/u9534644866_A_modern_luxury_home_exterior_with_a_sleek_garage_487a76ef-f23e-4ea3-9d35-bba43fa61724_3.png",
  byt1: "/images/u9534644866_A_chic_and_modern_Parisian_apartment_with_sleek_m_978ddd7e-c1ba-47fd-b9f6-3d3e92409162_1.png",
  byt2: "/images/u9534644866_A_contemporary_apartment_interior_with_three_dist_cbb61a6d-dc86-4aeb-8b9c-7c02268c90fb_3.png",
  byt3: "/images/u9534644866_A_contemporary_apartment_interior_with_three_dist_5c88f539-845f-40a3-957d-755e1f886c9d_0.png",
  byt4: "/images/u9534644866_A_contemporary_apartment_interior_with_three_dist_5c88f539-845f-40a3-957d-755e1f886c9d_1.png",
  byt5: "/images/u9534644866_A_contemporary_apartment_interior_with_three_dist_5c88f539-845f-40a3-957d-755e1f886c9d_2.png",
  byt6: "/images/u9534644866_A_beautifully_designed_apartment_in_France_blendi_b6767da1-246c-43e4-bda5-1b7ed1494a0e_0.png",
  cliff: "/images/u9534644866_A_breathtaking_luxury_home_situated_on_a_cliff_ov_49285e88-92e2-4ca6-8e94-94757d312049_1.png",
};

const defaultExtras: Partial<Property> = {
  brokerPhone: "+420 777 123 456",
  brokerEmail: "makler@nemovizor.cz",
  images: [],
  matterportUrl: "https://my.matterport.com/show/?m=uytiDYBAduT",
  pointsOfInterest: poiMale,
  condition: "Velmi dobrý",
  ownership: "Osobní",
  furnishing: "Částečně",
  energyRating: "C",
  parking: "Garáž",
  balcony: false,
  terrace: false,
  garden: false,
  elevator: false,
  cellar: false,
  garage: false,
  pool: false,
  loggia: false,
  views: 0,
  viewsTrend: "normal" as const,
  active: true,
};

export const properties: Property[] = [
  {
    ...defaultExtras as Property,
    id: "p1",
    slug: "premium-vila-praha-6-stresovice",
    title: "Prémiová vila se zahradou a výhledem",
    city: "Praha",
    district: "Praha 6 - Střešovice",
    locationLabel: "Praha 6, 245 m²",
    listingType: "sale",
    category: "house",
    subtype: "Vila",
    price: 9890000,
    area: 245,
    landArea: 400,
    roomsLabel: "6+kk",
    featured: true,
    views: 847,
    viewsTrend: "hot",
    active: true,
    summary: "Rodinná vila po rekonstrukci s privátní zahradou, dvojgaráží a klidnou adresou. Dispozice zahrnuje 3 ložnice, prostorný obývací pokoj s krbem, moderní kuchyni a 2 koupelny. Zahrada 400 m² s terasou a altánem.",
    brokerName: "Jan Novák",
    brokerPhone: "+420 777 111 222",
    brokerEmail: "jan.novak@nemovizor.cz",
    agencyName: "Nemovizor Prime",
    brokerId: "b1",
    latitude: 50.0948,
    longitude: 14.3805,
    imageSrc: img.vila1,
    imageAlt: "Luxusní rodinný dům",
    images: [img.vila4, img.vila5, img.cliff, img.dum1, img.byt1],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    matterportUrl: "https://my.matterport.com/show/?m=uytiDYBAduT",
    pointsOfInterest: poiPraha,
    condition: "Po rekonstrukci",
    ownership: "Osobní",
    furnishing: "Bez vybavení",
    energyRating: "B",
    buildingMaterial: "Cihlová",
    heating: ["Plynové"],
    parking: "Dvojgaráž",
    balcony: true,
    terrace: true,
    garden: true,
    elevator: false,
    cellar: true,
    garage: true,
    pool: false,
    loggia: false,
    yearBuilt: 1985,
    lastRenovation: 2023,
    totalFloors: 2,
  },
  {
    ...defaultExtras as Property,
    id: "p2",
    slug: "moderni-vila-brno",
    title: "Moderní vila v Brně",
    city: "Brno",
    district: "Brno - Královo Pole",
    locationLabel: "Brno, 320 m²",
    listingType: "sale",
    category: "house",
    subtype: "Vila",
    price: 12500000,
    area: 320,
    landArea: 800,
    roomsLabel: "7+1",
    featured: true,
    views: 623,
    viewsTrend: "hot",
    active: true,
    summary: "Hypermoderní vila s futuristickou architekturou. Otevřený plán, floor-to-ceiling okna, smart-home systém. Zahrada s bazénem a venkovním posezením. Garáž pro 2 auta.",
    brokerName: "Tereza Svobodová",
    brokerPhone: "+420 777 222 333",
    brokerEmail: "tereza.svobodova@nemovizor.cz",
    agencyName: "Nemovizor Prime",
    brokerId: "b2",
    latitude: 49.2122,
    longitude: 16.5968,
    imageSrc: img.vila2,
    imageAlt: "Moderní vila",
    images: [img.vila3, img.cliff, img.vila5, img.byt2],
    matterportUrl: "https://my.matterport.com/show/?m=uytiDYBAduT",
    pointsOfInterest: poiBrno,
    condition: "Novostavba",
    ownership: "Osobní",
    furnishing: "Plně vybaveno",
    energyRating: "A",
    buildingMaterial: "Montovaná",
    heating: ["Tepelné čerpadlo"],
    parking: "Dvojgaráž",
    balcony: true,
    terrace: true,
    garden: true,
    elevator: false,
    cellar: true,
    garage: true,
    pool: true,
    loggia: false,
    yearBuilt: 2024,
    totalFloors: 3,
  },
  {
    ...defaultExtras as Property,
    id: "p3",
    slug: "luxusni-byt-praha-2",
    title: "Luxusní byt 3+kk v srdci Prahy",
    city: "Praha",
    district: "Praha 2 - Vinohrady",
    locationLabel: "Praha 2, 110 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "3+kk",
    price: 7300000,
    area: 110,
    roomsLabel: "3+kk",
    featured: true,
    views: 312,
    viewsTrend: "warm",
    active: true,
    summary: "Světlý byt po citlivé renovaci s vysokými stropy a klidným vnitroblokem. Parketové podlahy, štuky, moderní kuchyně. Sklep a kočárkárna v ceně.",
    brokerName: "Lucie Hálová",
    brokerPhone: "+420 777 333 444",
    brokerEmail: "lucie.halova@nemovizor.cz",
    agencyName: "Nemovizor Prime",
    brokerId: "b3",
    latitude: 50.075,
    longitude: 14.431,
    imageSrc: img.byt1,
    imageAlt: "Luxusní byt",
    images: [img.byt3, img.byt4, img.byt5, img.byt6],
    pointsOfInterest: poiPraha,
    condition: "Po rekonstrukci",
    ownership: "Osobní",
    furnishing: "Částečně",
    energyRating: "C",
    buildingMaterial: "Cihlová",
    heating: ["Ústřední"],
    parking: "Ne",
    balcony: true,
    terrace: false,
    garden: false,
    elevator: true,
    cellar: true,
    garage: false,
    pool: false,
    loggia: false,
    floor: 3,
    totalFloors: 5,
    yearBuilt: 1920,
    lastRenovation: 2022,
  },
  {
    ...defaultExtras as Property,
    id: "p4",
    slug: "moderni-dum-praha-5-garaz",
    title: "Moderní dům s garáží",
    city: "Praha",
    district: "Praha 5 - Smíchov",
    locationLabel: "Praha 5, 210 m²",
    listingType: "sale",
    category: "house",
    subtype: "Rodinný",
    price: 11750000,
    area: 210,
    landArea: 250,
    roomsLabel: "5+kk",
    featured: true,
    views: 956,
    viewsTrend: "hot",
    active: true,
    summary: "Moderní dům s garáží, velkým obývacím prostorem a rychlým napojením do centra. Tři patra, zahrada 250 m², krytá terasa s grilem.",
    brokerName: "Martin Veselý",
    brokerPhone: "+420 777 444 555",
    brokerEmail: "martin.vesely@nemovizor.cz",
    agencyName: "Nemovizor Prime",
    brokerId: "b4",
    latitude: 50.0685,
    longitude: 14.3656,
    imageSrc: img.dum1,
    imageAlt: "Moderní dům s garáží",
    images: [img.dum2, img.dum3, img.vila1, img.byt2, img.cliff],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    pointsOfInterest: poiPraha,
    condition: "Novostavba",
    ownership: "Osobní",
    furnishing: "Bez vybavení",
    energyRating: "A",
    buildingMaterial: "Cihlová",
    heating: ["Tepelné čerpadlo"],
    parking: "Garáž",
    balcony: false,
    terrace: true,
    garden: true,
    elevator: false,
    cellar: true,
    garage: true,
    pool: false,
    loggia: false,
    yearBuilt: 2023,
    totalFloors: 3,
  },
  {
    ...defaultExtras as Property,
    id: "p5",
    slug: "luxusni-vila-ceske-budejovice-bazen",
    title: "Luxusní vila s bazénem",
    city: "České Budějovice",
    district: "České Budějovice - centrum",
    locationLabel: "České Budějovice, 380 m²",
    listingType: "sale",
    category: "house",
    subtype: "Vila",
    price: 15900000,
    area: 380,
    landArea: 1200,
    roomsLabel: "8+1",
    featured: true,
    active: true,
    summary: "Reprezentativní vila s bazénem, wellness zónou a velkou zahradou. Mramorové podlahy, domácí kino, vinný sklep. Pozemek 1200 m².",
    brokerName: "Petr Doležal",
    brokerPhone: "+420 777 555 666",
    brokerEmail: "petr.dolezal@nemovizor.cz",
    agencyName: "Nemovizor Prime",
    brokerId: "b5",
    latitude: 48.9747,
    longitude: 14.4747,
    imageSrc: img.vila4,
    imageAlt: "Luxusní vila s bazénem",
    showAgencyLogo: true,
    images: [img.vila5, img.vila1, img.cliff, img.dum2, img.byt3],
    condition: "Velmi dobrý",
    ownership: "Osobní",
    furnishing: "Plně vybaveno",
    energyRating: "B",
    buildingMaterial: "Cihlová",
    heating: ["Plynové"],
    parking: "Trojgaráž",
    balcony: true,
    terrace: true,
    garden: true,
    elevator: true,
    cellar: true,
    garage: true,
    pool: true,
    loggia: false,
    yearBuilt: 2010,
    lastRenovation: 2021,
    totalFloors: 3,
  },
  {
    ...defaultExtras as Property,
    id: "p6",
    slug: "moderni-apartman-praha-1",
    title: "Moderní apartmán v centru Prahy",
    city: "Praha",
    district: "Praha 1 - Staré Město",
    locationLabel: "Praha 1, 125 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "4+kk",
    price: 8200000,
    area: 125,
    roomsLabel: "4+kk",
    featured: true,
    active: true,
    summary: "Elegantní apartmán v prémiové adrese s důrazem na design a městský komfort. Střešní terasa s výhledem na Pražský hrad. Klimatizace, podlahové topení.",
    brokerName: "Barbora Jelínková",
    brokerPhone: "+420 777 666 777",
    brokerEmail: "barbora.jelinkova@nemovizor.cz",
    agencyName: "Nemovizor Prime",
    brokerId: "b6",
    latitude: 50.087,
    longitude: 14.421,
    imageSrc: img.byt2,
    imageAlt: "Moderní apartmán",
    images: [img.byt1, img.byt5, img.byt6, img.cliff],
    pointsOfInterest: poiPraha,
    condition: "Novostavba",
    ownership: "Osobní",
    furnishing: "Plně vybaveno",
    energyRating: "A",
    buildingMaterial: "Skeletová",
    heating: ["Podlahové"],
    parking: "Podzemní garáž",
    balcony: false,
    terrace: true,
    garden: false,
    elevator: true,
    cellar: true,
    garage: true,
    pool: false,
    loggia: true,
    floor: 5,
    totalFloors: 6,
    yearBuilt: 2022,
  },
];

export const featuredProperties = properties.filter((p) => p.featured);

export const latestProperties: Property[] = [
  {
    ...defaultExtras as Property,
    id: "n1",
    slug: "designovy-byt-praha-5",
    title: "Designový byt 2+kk",
    city: "Praha",
    district: "Praha 5 - Košíře",
    locationLabel: "Praha 5, 65 m²",
    listingType: "rent",
    category: "apartment",
    subtype: "2+kk",
    price: 25000,
    area: 65,
    roomsLabel: "2+kk",
    featured: false,
    views: 289,
    viewsTrend: "warm",
    active: true,
    summary: "Moderní byt v novostavbě s balkonem a výhledem do zeleně. Plně vybavený, včetně myčky a pračky.",
    brokerName: "Jan Novák",
    agencyName: "Nemovizor Prime",
    brokerId: "b1",
    latitude: 50.065,
    longitude: 14.375,
    imageSrc: img.byt6,
    imageAlt: "Designový byt",
    images: [img.byt3, img.byt4, img.byt5],
    balcony: true,
    elevator: true,
    floor: 4,
    totalFloors: 8,
    yearBuilt: 2021,
    furnishing: "Plně vybaveno",
    buildingMaterial: "Panelová",
    heating: ["Ústřední"],
  },
  {
    ...defaultExtras as Property,
    id: "n2",
    slug: "moderni-dum-olomouc",
    title: "Moderní dům 5+1",
    city: "Olomouc",
    district: "Olomouc - Neředín",
    locationLabel: "Olomouc, 180 m²",
    listingType: "sale",
    category: "house",
    subtype: "Rodinný",
    price: 8900000,
    area: 180,
    landArea: 350,
    roomsLabel: "5+1",
    featured: false,
    active: true,
    summary: "Prostorný dům s garáží na klidném místě. Zahrada, sklep, dva balkony.",
    brokerName: "Tereza Svobodová",
    agencyName: "Nemovizor Prime",
    brokerId: "b2",
    latitude: 49.595,
    longitude: 17.251,
    imageSrc: img.dum2,
    imageAlt: "Moderní dům",
    images: [img.dum3, img.dum1, img.vila2],
    garden: true,
    terrace: true,
    balcony: true,
    garage: true,
    cellar: true,
    totalFloors: 2,
    yearBuilt: 2019,
    buildingMaterial: "Cihlová",
    heating: ["Plynové"],
  },
  {
    ...defaultExtras as Property,
    id: "n3",
    slug: "luxusni-apartman-karlovy-vary",
    title: "Luxusní apartmán",
    city: "Karlovy Vary",
    district: "Karlovy Vary - centrum",
    locationLabel: "Karlovy Vary, 95 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "3+kk",
    price: 6750000,
    area: 95,
    roomsLabel: "3+kk",
    featured: false,
    views: 541,
    viewsTrend: "hot",
    active: true,
    summary: "Apartmán s kolonádním výhledem, po kompletní rekonstrukci. Ideální jako investice.",
    brokerName: "Lucie Hálová",
    agencyName: "Nemovizor Prime",
    brokerId: "b3",
    latitude: 50.2297,
    longitude: 12.8717,
    imageSrc: img.byt3,
    imageAlt: "Luxusní apartmán",
    images: [img.byt4, img.byt5, img.byt1],
    elevator: true,
    cellar: true,
    floor: 2,
    totalFloors: 4,
    yearBuilt: 1895,
    lastRenovation: 2023,
    condition: "Po rekonstrukci",
    buildingMaterial: "Cihlová",
    heating: ["Ústřední"],
  },
  {
    ...defaultExtras as Property,
    id: "n4",
    slug: "prostorny-byt-brno",
    title: "Prostorný byt 3+1",
    city: "Brno",
    district: "Brno - Žabovřesky",
    locationLabel: "Brno, 88 m²",
    listingType: "rent",
    category: "apartment",
    subtype: "3+1",
    price: 22000,
    area: 88,
    roomsLabel: "3+1",
    featured: false,
    active: true,
    summary: "Prostorný byt v žádané lokalitě. Nová kuchyně, parkety, sklep. Blízko MHD.",
    brokerName: "Martin Veselý",
    agencyName: "Nemovizor Prime",
    brokerId: "b4",
    latitude: 49.208,
    longitude: 16.583,
    imageSrc: img.byt4,
    imageAlt: "Prostorný byt",
    images: [img.byt3, img.byt5, img.byt6],
    elevator: false,
    cellar: true,
    floor: 2,
    totalFloors: 4,
    yearBuilt: 1975,
    lastRenovation: 2020,
    balcony: true,
    buildingMaterial: "Panelová",
    heating: ["Ústřední"],
  },
  {
    ...defaultExtras as Property,
    id: "n5",
    slug: "moderni-interier-hradec-kralove",
    title: "Moderní interiér 2+kk",
    city: "Hradec Králové",
    district: "Hradec Králové - centrum",
    locationLabel: "Hradec Králové, 62 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "2+kk",
    price: 4850000,
    area: 62,
    roomsLabel: "2+kk",
    featured: false,
    active: true,
    summary: "Byt v centru s moderním designem. Velká okna, vestavěné skříně, nízké náklady.",
    brokerName: "Petr Doležal",
    agencyName: "Nemovizor Prime",
    brokerId: "b5",
    latitude: 50.2094,
    longitude: 15.8327,
    imageSrc: img.byt5,
    imageAlt: "Moderní interiér",
    images: [img.byt3, img.byt4, img.byt6],
    elevator: true,
    floor: 3,
    totalFloors: 6,
    yearBuilt: 2018,
    energyRating: "B",
    buildingMaterial: "Skeletová",
    heating: ["Ústřední"],
  },
  {
    ...defaultExtras as Property,
    id: "n6",
    slug: "novy-dum-plzen",
    title: "Novostavba 5+kk",
    city: "Plzeň",
    district: "Plzeň - Slovany",
    locationLabel: "Plzeň, 205 m²",
    listingType: "sale",
    category: "house",
    subtype: "Rodinný",
    price: 9150000,
    area: 205,
    landArea: 450,
    roomsLabel: "5+kk",
    featured: false,
    active: true,
    summary: "Novostavba v klidné vilové čtvrti. Tepelné čerpadlo, rekuperace, fotovoltaika na střeše.",
    brokerName: "Barbora Jelínková",
    agencyName: "Nemovizor Prime",
    brokerId: "b6",
    latitude: 49.738,
    longitude: 13.378,
    imageSrc: img.dum3,
    imageAlt: "Nový dům",
    images: [img.dum1, img.dum2, img.vila3, img.cliff],
    garden: true,
    terrace: true,
    garage: true,
    cellar: true,
    totalFloors: 2,
    yearBuilt: 2025,
    energyRating: "A",
    condition: "Novostavba",
    parking: "Dvojgaráž",
    buildingMaterial: "Dřevostavba",
    heating: ["Tepelné čerpadlo"],
  },
  {
    ...defaultExtras as Property,
    id: "n7",
    slug: "drazbovy-byt-ostrava",
    title: "Dražba bytu 2+1 v Ostravě",
    city: "Ostrava",
    district: "Ostrava - Poruba",
    locationLabel: "Ostrava, 58 m²",
    listingType: "auction",
    category: "apartment",
    subtype: "2+1",
    price: 1450000,
    area: 58,
    roomsLabel: "2+1",
    featured: false,
    views: 412,
    viewsTrend: "hot",
    active: true,
    summary: "Dražba bytu v panelovém domě po částečné rekonstrukci. Nová plastová okna, koupelna po renovaci. Vyvolávací cena výrazně pod tržní hodnotou.",
    brokerName: "Tomáš Krejčí",
    agencyName: "RE/MAX Horizont",
    brokerId: "b7",
    latitude: 49.8209,
    longitude: 18.1725,
    imageSrc: img.byt4,
    imageAlt: "Dražbový byt Ostrava",
    images: [img.byt3, img.byt5, img.byt6],
    elevator: true,
    cellar: true,
    floor: 7,
    totalFloors: 12,
    yearBuilt: 1978,
    lastRenovation: 2021,
    buildingMaterial: "Panelová",
    heating: ["Ústřední"],
  },
  {
    ...defaultExtras as Property,
    id: "n8",
    slug: "developersky-projekt-praha-9",
    title: "Nový bytový projekt Zelená Vysočany",
    city: "Praha",
    district: "Praha 9 - Vysočany",
    locationLabel: "Praha 9, 45–120 m²",
    listingType: "project",
    category: "apartment",
    subtype: "1+kk – 4+kk",
    price: 5200000,
    area: 75,
    roomsLabel: "2+kk",
    featured: false,
    views: 734,
    viewsTrend: "hot",
    active: true,
    summary: "Developerský projekt 120 bytů v energeticky úsporném komplexu. Dokončení Q4 2026. Podzemní garáže, společná zahrada, dětské hřiště. Byty od 1+kk do 4+kk.",
    brokerName: "Martin Veselý",
    agencyName: "Nemovizor Prime",
    brokerId: "b4",
    latitude: 50.1065,
    longitude: 14.4975,
    imageSrc: img.vila3,
    imageAlt: "Bytový projekt Vysočany",
    images: [img.byt1, img.byt2, img.dum1, img.vila2],
    condition: "Novostavba",
    energyRating: "A",
    buildingMaterial: "Monolitická",
    heating: ["Tepelné čerpadlo"],
    parking: "Podzemní garáž",
    elevator: true,
    balcony: true,
    totalFloors: 8,
    yearBuilt: 2026,
  },
  {
    ...defaultExtras as Property,
    id: "n9",
    slug: "podilovy-dum-liberec",
    title: "Podíl 1/4 na rodinném domě",
    city: "Liberec",
    district: "Liberec - Rochlice",
    locationLabel: "Liberec, 180 m²",
    listingType: "shares",
    category: "house",
    subtype: "Rodinný",
    price: 2100000,
    area: 180,
    landArea: 600,
    roomsLabel: "5+1",
    featured: false,
    views: 187,
    viewsTrend: "warm",
    active: true,
    summary: "Prodej ideálního podílu 1/4 na rodinném domě. Dům je v dobrém stavu, zahrada 600 m². Vhodné pro investory nebo spoluvlastníky.",
    brokerName: "Ondřej Fiala",
    agencyName: "Century 21 Bonus",
    brokerId: "b9",
    latitude: 50.7572,
    longitude: 15.0543,
    imageSrc: img.dum2,
    imageAlt: "Podílový dům Liberec",
    images: [img.dum3, img.dum1, img.vila5],
    garden: true,
    cellar: true,
    garage: true,
    totalFloors: 2,
    yearBuilt: 1965,
    lastRenovation: 2015,
    buildingMaterial: "Cihlová",
    heating: ["Plynové"],
  },
  {
    ...defaultExtras as Property,
    id: "n10",
    slug: "penthouse-brno-stred",
    title: "Penthouse s terasou a výhledem",
    city: "Brno",
    district: "Brno - střed",
    locationLabel: "Brno, 145 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "4+kk",
    price: 13800000,
    area: 145,
    roomsLabel: "4+kk",
    featured: false,
    views: 892,
    viewsTrend: "hot",
    active: true,
    summary: "Exkluzivní penthouse v centru Brna. Terasa 60 m² s panoramatickým výhledem, privátní výtah, smart home. Garáž pro 2 auta v ceně.",
    brokerName: "Tereza Svobodová",
    agencyName: "Nemovizor Prime",
    brokerId: "b2",
    latitude: 49.1951,
    longitude: 16.6068,
    imageSrc: img.byt2,
    imageAlt: "Penthouse Brno",
    images: [img.byt1, img.byt6, img.cliff, img.vila4],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    condition: "Novostavba",
    ownership: "Osobní",
    furnishing: "Plně vybaveno",
    energyRating: "A",
    buildingMaterial: "Monolitická",
    heating: ["Podlahové"],
    parking: "Podzemní garáž",
    terrace: true,
    elevator: true,
    garage: true,
    loggia: true,
    floor: 12,
    totalFloors: 12,
    yearBuilt: 2025,
  },
  {
    ...defaultExtras as Property,
    id: "n11",
    slug: "stavebni-pozemek-ricany",
    title: "Stavební pozemek 850 m²",
    city: "Praha",
    district: "Říčany u Prahy",
    locationLabel: "Říčany, 850 m²",
    listingType: "sale",
    category: "land",
    subtype: "Pozemek",
    price: 4250000,
    area: 850,
    landArea: 850,
    roomsLabel: "—",
    featured: false,
    active: true,
    summary: "Rovinatý stavební pozemek s inženýrskými sítěmi na hranici. Územní plán umožňuje RD i dvojdům. Klidná lokalita, 20 min do centra Prahy.",
    brokerName: "Jan Novák",
    agencyName: "Nemovizor Prime",
    brokerId: "b1",
    latitude: 49.9918,
    longitude: 14.6539,
    imageSrc: img.cliff,
    imageAlt: "Pozemek Ricany",
    images: [img.dum1, img.vila4],
    condition: "Původní",
    ownership: "Osobní",
    parking: "Ne",
    yearBuilt: undefined,
  },
  {
    ...defaultExtras as Property,
    id: "n12",
    slug: "pronajem-komerce-praha-4",
    title: "Komerční prostor 200 m²",
    city: "Praha",
    district: "Praha 4 - Nusle",
    locationLabel: "Praha 4, 200 m²",
    listingType: "rent",
    category: "commercial",
    subtype: "Komerční",
    price: 45000,
    area: 200,
    roomsLabel: "—",
    featured: false,
    views: 156,
    viewsTrend: "warm",
    active: true,
    summary: "Obchodní prostor na frekventované ulici. Velké výlohy, vysoké stropy, klimatizace. Vhodné pro showroom, kavárnu nebo kanceláře.",
    brokerName: "Barbora Jelínková",
    agencyName: "Nemovizor Prime",
    brokerId: "b6",
    latitude: 50.0595,
    longitude: 14.4300,
    imageSrc: img.byt3,
    imageAlt: "Komerční prostor Praha",
    images: [img.byt4, img.byt5, img.byt1],
    condition: "Po rekonstrukci",
    energyRating: "C",
    buildingMaterial: "Cihlová",
    heating: ["Klimatizace"],
    parking: "Před budovou",
    elevator: true,
    floor: 0,
    totalFloors: 5,
    yearBuilt: 1930,
    lastRenovation: 2023,
  },
  {
    ...defaultExtras as Property,
    id: "n13",
    slug: "chalupa-sumava",
    title: "Zrekonstruovaná chalupa na Šumavě",
    city: "Kašperské Hory",
    district: "Kašperské Hory",
    locationLabel: "Kašperské Hory, 120 m²",
    listingType: "sale",
    category: "house",
    subtype: "Chalupa",
    price: 3950000,
    area: 120,
    landArea: 2500,
    roomsLabel: "4+1",
    featured: false,
    views: 378,
    viewsTrend: "warm",
    active: true,
    summary: "Krásná chalupa po citlivé rekonstrukci v srdci Šumavy. Kamenné zdi, trámové stropy, moderní zázemí. Pozemek 2500 m² s ovocným sadem.",
    brokerName: "Ondřej Fiala",
    agencyName: "Century 21 Bonus",
    brokerId: "b9",
    latitude: 49.1425,
    longitude: 13.5559,
    imageSrc: img.vila5,
    imageAlt: "Chalupa Sumava",
    images: [img.dum3, img.cliff, img.vila1],
    garden: true,
    terrace: true,
    cellar: true,
    totalFloors: 2,
    yearBuilt: 1850,
    lastRenovation: 2022,
    condition: "Po rekonstrukci",
    buildingMaterial: "Kamenná",
    heating: ["Kamna na dřevo", "Elektrické"],
  },
  {
    ...defaultExtras as Property,
    id: "n14",
    slug: "investicni-byt-usti-nad-labem",
    title: "Investiční byt 1+kk",
    city: "Ústí nad Labem",
    district: "Ústí nad Labem - centrum",
    locationLabel: "Ústí n. L., 32 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "1+kk",
    price: 1290000,
    area: 32,
    roomsLabel: "1+kk",
    featured: false,
    views: 267,
    viewsTrend: "warm",
    active: true,
    summary: "Kompaktní byt ideální jako investice s garantovaným pronájmem. Výnos 6,5 % ročně. Po rekonstrukci, ihned volný.",
    brokerName: "Petra Němcová",
    agencyName: "RE/MAX Horizont",
    brokerId: "b8",
    latitude: 50.6611,
    longitude: 14.0531,
    imageSrc: img.byt6,
    imageAlt: "Investiční byt Ústí",
    images: [img.byt3, img.byt5],
    elevator: false,
    cellar: true,
    floor: 3,
    totalFloors: 5,
    yearBuilt: 1960,
    lastRenovation: 2024,
    condition: "Po rekonstrukci",
    buildingMaterial: "Cihlová",
    heating: ["Ústřední"],
  },
  {
    ...defaultExtras as Property,
    id: "n15",
    slug: "drazba-komerce-pardubice",
    title: "Dražba komerčního objektu",
    city: "Pardubice",
    district: "Pardubice - Zelené Předměstí",
    locationLabel: "Pardubice, 450 m²",
    listingType: "auction",
    category: "commercial",
    subtype: "Komerční",
    price: 6800000,
    area: 450,
    landArea: 300,
    roomsLabel: "—",
    featured: false,
    views: 89,
    viewsTrend: "normal",
    active: true,
    summary: "Dražba komerčního objektu v centru Pardubic. Bývalá restaurace s kuchyní, sálem a terasou. Pozemek 300 m². Vyvolávací cena pod odhadem.",
    brokerName: "Tomáš Krejčí",
    agencyName: "RE/MAX Horizont",
    brokerId: "b7",
    latitude: 50.0343,
    longitude: 15.7742,
    imageSrc: img.dum1,
    imageAlt: "Komerční objekt Pardubice",
    images: [img.dum2, img.byt1, img.vila3],
    condition: "Dobrý",
    buildingMaterial: "Cihlová",
    heating: ["Plynové"],
    parking: "Vlastní parkoviště",
    totalFloors: 2,
    yearBuilt: 1935,
  },
  {
    ...defaultExtras as Property,
    id: "n16",
    slug: "projekt-rezidence-olomouc",
    title: "Rezidence Na Kopečku – byty od 2+kk",
    city: "Olomouc",
    district: "Olomouc - Hejčín",
    locationLabel: "Olomouc, 55–110 m²",
    listingType: "project",
    category: "apartment",
    subtype: "2+kk – 4+kk",
    price: 4500000,
    area: 68,
    roomsLabel: "2+kk",
    featured: false,
    views: 523,
    viewsTrend: "hot",
    active: true,
    summary: "Komorní projekt 24 bytů v klidné rezidenční čtvrti. Cihlové zdivo, velké balkony, privátní zahrádky v přízemí. Dokončení jaro 2027.",
    brokerName: "Petra Němcová",
    agencyName: "RE/MAX Horizont",
    brokerId: "b8",
    latitude: 49.6050,
    longitude: 17.2400,
    imageSrc: img.vila2,
    imageAlt: "Rezidence Olomouc",
    images: [img.byt2, img.byt6, img.dum3, img.vila4],
    condition: "Novostavba",
    energyRating: "A",
    buildingMaterial: "Cihlová",
    heating: ["Tepelné čerpadlo"],
    parking: "Podzemní garáž",
    elevator: true,
    balcony: true,
    garden: true,
    totalFloors: 5,
    yearBuilt: 2027,
  },
  // ===== REÁLNÉ NABÍDKY (Sreality) =====
  {
    ...defaultExtras as Property,
    id: "real-1",
    slug: "prodej-bytu-2-1-koprivnice",
    title: "Prodej bytu 2+1 56 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "Byt",
    roomsLabel: "2+1",
    area: 56,
    price: 2490000,
    imageSrc: "/images/real-koprivnice-2+1.jpg",
    imageAlt: "Byt 2+1 Kopřivnice",
    images: [
      "/images/real-koprivnice-2+1.jpg",
    ],
    city: "Kopřivnice",
    district: "Kopřivnice",
    locationLabel: "Družební, Kopřivnice",
    latitude: 49.605331,
    longitude: 18.141354,
    summary: "Prodej bytu 2+1 o celkové výměře 56 m² v klidné lokalitě Kopřivnice. Byt se nachází v zatepleném panelovém domě s novými okny.",
    featured: false,
    brokerName: "Sreality",
    agencyName: "Reálná nabídka",
    condition: "Dobrý",
    ownership: "Osobní",
    energyRating: "D",
  },
  {
    ...defaultExtras as Property,
    id: "real-2",
    slug: "prodej-bytu-3-kk-praha-9-cerny-most",
    title: "Prodej bytu 3+kk 60 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "Byt",
    roomsLabel: "3+kk",
    area: 60,
    price: 7990000,
    imageSrc: "/images/real-praha9-3+kk.jpg",
    imageAlt: "Byt 3+kk Praha 9",
    images: [
      "/images/real-praha9-3+kk.jpg",
    ],
    city: "Praha",
    district: "Praha 9 - Černý Most",
    locationLabel: "Vašátkova, Praha 9 - Černý Most",
    latitude: 50.102592,
    longitude: 14.57009,
    summary: "Prostorný byt 3+kk o výměře 60 m² v Praze 9 - Černém Mostě. Výborná dostupnost metra, kompletní občanská vybavenost v okolí.",
    featured: false,
    brokerName: "Sreality",
    agencyName: "Reálná nabídka",
    condition: "Po rekonstrukci",
    ownership: "Osobní",
    energyRating: "C",
    pointsOfInterest: poiPraha,
  },
  {
    ...defaultExtras as Property,
    id: "real-3",
    slug: "prodej-bytu-1-1-klasterec-nad-ohrim",
    title: "Prodej bytu 1+1 52 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "Byt",
    roomsLabel: "1+1",
    area: 52,
    price: 2100000,
    imageSrc: "/images/real-klasterec-1+1.jpg",
    imageAlt: "Byt 1+1 Klášterec nad Ohří",
    images: [
      "/images/real-klasterec-1+1.jpg",
    ],
    city: "Klášterec nad Ohří",
    district: "Miřetice u Klášterce",
    locationLabel: "Pražská, Klášterec nad Ohří",
    latitude: 50.383911,
    longitude: 13.194117,
    summary: "Byt 1+1 o výměře 52 m² v Klášterci nad Ohří. Klidná lokalita s dobrou dostupností centra města.",
    featured: false,
    brokerName: "Sreality",
    agencyName: "Reálná nabídka",
    condition: "Původní stav",
    ownership: "Osobní",
    energyRating: "E",
  },
  {
    ...defaultExtras as Property,
    id: "real-4",
    slug: "prodej-bytu-1-1-plzen-bolevec",
    title: "Prodej bytu 1+1 39 m²",
    listingType: "sale",
    category: "apartment",
    subtype: "Byt",
    roomsLabel: "1+1",
    area: 39,
    price: 3995000,
    imageSrc: "/images/real-plzen-1+1.jpg",
    imageAlt: "Byt 1+1 Plzeň",
    images: [
      "/images/real-plzen-1+1.jpg",
    ],
    city: "Plzeň",
    district: "Plzeň - Bolevec",
    locationLabel: "Tachovská, Plzeň - Bolevec",
    latitude: 49.781727,
    longitude: 13.376747,
    summary: "Byt 1+1 o výměře 39 m² v Plzni - Bolevci. Sídlištní zástavba s kompletní občanskou vybaveností a blízkostí přírody.",
    featured: false,
    brokerName: "Sreality",
    agencyName: "Reálná nabídka",
    condition: "Dobrý",
    ownership: "Osobní",
    energyRating: "D",
  },
  // ===== 150 DALŠÍCH NABÍDEK =====
  ...generateBulkProperties(),
];

function generateBulkProperties(): Property[] {
  const cities = [
    { city: "Praha", districts: ["Praha 3 - Žižkov","Praha 4 - Nusle","Praha 6 - Dejvice","Praha 7 - Holešovice","Praha 8 - Karlín","Praha 9 - Vysočany","Praha 10 - Vršovice","Praha 5 - Barrandov"], lat: 50.08, lon: 14.42 },
    { city: "Brno", districts: ["Brno - Černá Pole","Brno - Bystrc","Brno - Komín","Brno - Řečkovice"], lat: 49.20, lon: 16.61 },
    { city: "Ostrava", districts: ["Ostrava - Mariánské Hory","Ostrava - Moravská Ostrava","Ostrava - Hrabůvka"], lat: 49.82, lon: 18.26 },
    { city: "Plzeň", districts: ["Plzeň - Bory","Plzeň - Doubravka","Plzeň - Lochotín"], lat: 49.74, lon: 13.38 },
    { city: "Liberec", districts: ["Liberec - Vratislavice","Liberec - Ruprechtice"], lat: 50.77, lon: 15.06 },
    { city: "Olomouc", districts: ["Olomouc - Slavonín","Olomouc - Nová Ulice"], lat: 49.59, lon: 17.25 },
    { city: "České Budějovice", districts: ["České Budějovice - Suché Vrbné","České Budějovice - Rožnov"], lat: 48.97, lon: 14.47 },
    { city: "Hradec Králové", districts: ["Hradec Králové - Malšovice","Hradec Králové - Pouchov"], lat: 50.21, lon: 15.83 },
    { city: "Pardubice", districts: ["Pardubice - Polabiny","Pardubice - Studánka"], lat: 50.03, lon: 15.77 },
    { city: "Zlín", districts: ["Zlín - centrum","Zlín - Jižní Svahy"], lat: 49.22, lon: 17.67 },
    { city: "Jihlava", districts: ["Jihlava - centrum"], lat: 49.40, lon: 15.59 },
    { city: "Karlovy Vary", districts: ["Karlovy Vary - Drahovice"], lat: 50.23, lon: 12.87 },
    { city: "Ústí nad Labem", districts: ["Ústí n.L. - Střekov","Ústí n.L. - Krásné Březno"], lat: 50.66, lon: 14.04 },
    { city: "Kladno", districts: ["Kladno - centrum"], lat: 50.15, lon: 14.10 },
    { city: "Teplice", districts: ["Teplice - centrum"], lat: 50.64, lon: 13.82 },
    { city: "Znojmo", districts: ["Znojmo - centrum"], lat: 48.86, lon: 16.05 },
    { city: "Třebíč", districts: ["Třebíč - centrum"], lat: 49.22, lon: 15.88 },
    { city: "Opava", districts: ["Opava - centrum"], lat: 49.94, lon: 17.90 },
  ];

  const templates: Array<{
    listingType: Property["listingType"];
    category: Property["category"];
    subtype: string;
    rooms: string;
    areaRange: [number, number];
    priceRange: [number, number];
    featured: boolean;
  }> = [
    { listingType: "sale", category: "apartment", subtype: "2+kk", rooms: "2+kk", areaRange: [42, 68], priceRange: [2200000, 5800000], featured: false },
    { listingType: "sale", category: "apartment", subtype: "3+kk", rooms: "3+kk", areaRange: [65, 95], priceRange: [3500000, 8500000], featured: false },
    { listingType: "sale", category: "apartment", subtype: "1+kk", rooms: "1+kk", areaRange: [25, 40], priceRange: [1500000, 3500000], featured: false },
    { listingType: "sale", category: "apartment", subtype: "4+kk", rooms: "4+kk", areaRange: [90, 140], priceRange: [5000000, 12000000], featured: false },
    { listingType: "sale", category: "house", subtype: "Rodinný", rooms: "5+kk", areaRange: [140, 250], priceRange: [5500000, 14000000], featured: false },
    { listingType: "sale", category: "house", subtype: "Rodinný", rooms: "4+1", areaRange: [120, 180], priceRange: [4500000, 9000000], featured: false },
    { listingType: "rent", category: "apartment", subtype: "2+kk", rooms: "2+kk", areaRange: [45, 65], priceRange: [14000, 28000], featured: false },
    { listingType: "rent", category: "apartment", subtype: "3+1", rooms: "3+1", areaRange: [70, 95], priceRange: [18000, 35000], featured: false },
    { listingType: "rent", category: "apartment", subtype: "1+kk", rooms: "1+kk", areaRange: [25, 40], priceRange: [10000, 18000], featured: false },
    { listingType: "auction", category: "apartment", subtype: "2+1", rooms: "2+1", areaRange: [50, 70], priceRange: [900000, 2500000], featured: false },
    { listingType: "auction", category: "house", subtype: "Rodinný", rooms: "4+1", areaRange: [130, 200], priceRange: [2000000, 5500000], featured: false },
    { listingType: "project", category: "apartment", subtype: "2+kk – 4+kk", rooms: "2+kk", areaRange: [50, 100], priceRange: [3500000, 7000000], featured: false },
    { listingType: "shares", category: "house", subtype: "Rodinný", rooms: "4+1", areaRange: [150, 220], priceRange: [1200000, 3500000], featured: false },
    { listingType: "shares", category: "apartment", subtype: "3+1", rooms: "3+1", areaRange: [70, 90], priceRange: [800000, 2000000], featured: false },
    { listingType: "sale", category: "land", subtype: "Pozemek", rooms: "—", areaRange: [500, 2000], priceRange: [1500000, 8000000], featured: false },
    { listingType: "rent", category: "commercial", subtype: "Komerční", rooms: "—", areaRange: [80, 400], priceRange: [25000, 80000], featured: false },
    { listingType: "sale", category: "commercial", subtype: "Komerční", rooms: "—", areaRange: [100, 500], priceRange: [4000000, 15000000], featured: false },
    { listingType: "sale", category: "house", subtype: "Vila", rooms: "6+kk", areaRange: [200, 400], priceRange: [10000000, 25000000], featured: true },
    { listingType: "sale", category: "apartment", subtype: "2+1", rooms: "2+1", areaRange: [50, 72], priceRange: [2800000, 6000000], featured: false },
    { listingType: "rent", category: "house", subtype: "Rodinný", rooms: "4+kk", areaRange: [120, 200], priceRange: [30000, 55000], featured: false },
  ];

  const images = [img.vila1, img.vila2, img.vila3, img.vila4, img.vila5, img.dum1, img.dum2, img.dum3, img.byt1, img.byt2, img.byt3, img.byt4, img.byt5, img.byt6, img.cliff];
  const brokerIds = ["b1","b2","b3","b4","b5","b6","b7","b8","b9"];
  const brokerNames = ["Jan Novák","Tereza Svobodová","Lucie Hálová","Martin Veselý","Petr Doležal","Barbora Jelínková","Tomáš Krejčí","Petra Němcová","Ondřej Fiala"];
  const agencyNames = ["Nemovizor Prime","Nemovizor Prime","Nemovizor Prime","Nemovizor Prime","Nemovizor Prime","Nemovizor Prime","RE/MAX Horizont","RE/MAX Horizont","Century 21 Bonus"];
  const conditions = ["Novostavba","Po rekonstrukci","Velmi dobrý","Dobrý","Původní"];
  const materials = ["Cihlová","Panelová","Skeletová","Montovaná","Dřevostavba"];
  const heatings = [["Ústřední"],["Plynové"],["Tepelné čerpadlo"],["Podlahové"],["Elektrické"]];
  const energies = ["A","B","C","D"];
  const trends: Array<Property["viewsTrend"]> = ["hot","hot","warm","warm","warm","normal","normal","normal","normal","normal"];
  const titlePrefixes: Record<string, string[]> = {
    apartment: ["Světlý byt","Prostorný byt","Moderní byt","Útulný byt","Slunný byt","Cihlový byt","Nový byt","Zrekonstruovaný byt","Atraktivní byt","Mezonetový byt"],
    house: ["Rodinný dům","Moderní dům","Prostorný dům","Nový dům","Dům se zahradou","Dům s garáží","Řadový dům","Vilový dům","Patrový dům","Přízemní dům"],
    land: ["Stavební pozemek","Rovinatý pozemek","Pozemek se sítěmi","Pozemek v zástavbě","Investiční pozemek"],
    commercial: ["Kancelářské prostory","Obchodní prostor","Prodejní plocha","Restaurace","Skladové prostory"],
  };

  function seededRandom(seed: number) {
    let s = seed;
    return () => { s = (s * 16807 + 0) % 2147483647; return s / 2147483647; };
  }

  const result: Property[] = [];

  for (let i = 0; i < 150; i++) {
    const rand = seededRandom(i * 7919 + 42);
    const tpl = templates[i % templates.length];
    const cityData = cities[i % cities.length];
    const district = cityData.districts[Math.floor(rand() * cityData.districts.length)];
    const brokerIdx = Math.floor(rand() * brokerIds.length);
    const area = Math.round(tpl.areaRange[0] + rand() * (tpl.areaRange[1] - tpl.areaRange[0]));
    const price = Math.round((tpl.priceRange[0] + rand() * (tpl.priceRange[1] - tpl.priceRange[0])) / 10000) * 10000;
    const imgIdx = Math.floor(rand() * images.length);
    const imgIdx2 = (imgIdx + 3) % images.length;
    const imgIdx3 = (imgIdx + 7) % images.length;
    const imgIdx4 = (imgIdx + 11) % images.length;
    const prefixes = titlePrefixes[tpl.category] || ["Nemovitost"];
    const title = `${prefixes[i % prefixes.length]} ${tpl.rooms !== "—" ? tpl.rooms : area + " m²"}`;
    const slug = `${title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "")}-${cityData.city.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-")}-${i + 17}`;
    const latOffset = (rand() - 0.5) * 0.08;
    const lonOffset = (rand() - 0.5) * 0.08;
    const views = Math.round(rand() * 900 + 50);
    const trend = trends[Math.floor(rand() * trends.length)];

    result.push({
      ...defaultExtras as Property,
      id: `g${i + 17}`,
      slug,
      title,
      city: cityData.city,
      district,
      locationLabel: `${cityData.city}, ${area} m²`,
      listingType: tpl.listingType,
      category: tpl.category,
      subtype: tpl.subtype,
      price,
      area,
      landArea: tpl.category === "land" ? area : tpl.category === "house" ? Math.round(area * 1.5 + rand() * 300) : undefined,
      roomsLabel: tpl.rooms,
      featured: tpl.featured && i < 5,
      views,
      viewsTrend: trend,
      active: true,
      summary: `${title} v lokalitě ${district}. Plocha ${area} m², ${tpl.rooms !== "—" ? `dispozice ${tpl.rooms},` : ""} ${conditions[Math.floor(rand() * conditions.length)].toLowerCase()} stav.`,
      brokerName: brokerNames[brokerIdx],
      agencyName: agencyNames[brokerIdx],
      brokerId: brokerIds[brokerIdx],
      latitude: cityData.lat + latOffset,
      longitude: cityData.lon + lonOffset,
      imageSrc: images[imgIdx],
      imageAlt: title.normalize("NFD").replace(/[\u0300-\u036f]/g, ""),
      images: [images[imgIdx2], images[imgIdx3], images[imgIdx4]],
      condition: conditions[Math.floor(rand() * conditions.length)],
      energyRating: energies[Math.floor(rand() * energies.length)] as Property["energyRating"],
      buildingMaterial: materials[Math.floor(rand() * materials.length)],
      heating: heatings[Math.floor(rand() * heatings.length)],
      elevator: tpl.category === "apartment" && rand() > 0.4,
      balcony: tpl.category === "apartment" && rand() > 0.3,
      terrace: tpl.category === "house" && rand() > 0.4,
      garden: tpl.category === "house" && rand() > 0.3,
      garage: (tpl.category === "house" || tpl.category === "commercial") && rand() > 0.4,
      cellar: rand() > 0.3,
      pool: tpl.category === "house" && tpl.featured && rand() > 0.6,
      floor: tpl.category === "apartment" ? Math.floor(rand() * 10) + 1 : undefined,
      totalFloors: tpl.category === "apartment" ? Math.floor(rand() * 8) + 3 : tpl.category === "house" ? Math.floor(rand() * 2) + 1 : undefined,
      yearBuilt: Math.round(1950 + rand() * 75),
    });
  }

  return result;
}

// ===== REALITNÍ KANCELÁŘE =====

export const agencies: Agency[] = [
  {
    id: "a1",
    name: "Nemovizor Prime",
    slug: "nemovizor-prime",
    description: "Prémiová realitní kancelář zaměřená na exkluzivní nemovitosti v České republice. Nabízíme individuální přístup, profesionální marketing a kompletní právní servis. Naše portfolio zahrnuje luxusní vily, prémiové byty a komerční prostory ve všech krajských městech.",
    phone: "+420 800 100 200",
    email: "info@nemovizor-prime.cz",
    website: "https://www.nemovizor-prime.cz",
    foundedYear: 2010,
    totalBrokers: 6,
    totalListings: 81,
    totalDeals: 573,
    rating: 4.8,
    specializations: ["Luxusní nemovitosti", "Prémiové byty", "Komerční prostory", "Investiční poradenství"],
    isIndependent: false,
  },
  {
    id: "a2",
    name: "RE/MAX Horizont",
    slug: "remax-horizont",
    description: "Franšízová pobočka mezinárodní sítě RE/MAX. Působíme na Moravě se zaměřením na rezidenční nemovitosti. Díky globálnímu zázemí nabízíme mezinárodní marketing a přístup k zahraničním klientům.",
    phone: "+420 585 200 300",
    email: "info@remax-horizont.cz",
    website: "https://www.remax-horizont.cz",
    foundedYear: 2015,
    totalBrokers: 2,
    totalListings: 34,
    totalDeals: 210,
    rating: 4.6,
    specializations: ["Rezidenční nemovitosti", "Pronájmy", "Zahraniční klientela"],
    parentAgencyId: "a-remax-global",
    isIndependent: true,
  },
  {
    id: "a3",
    name: "Century 21 Bonus",
    slug: "century-21-bonus",
    description: "Pobočka mezinárodní sítě Century 21 pokrývající západní a jižní Čechy. Specializujeme se na rodinné domy, pozemky a rekreační objekty v atraktivních lokalitách.",
    phone: "+420 377 300 400",
    email: "info@century21bonus.cz",
    website: "https://www.century21bonus.cz",
    foundedYear: 2018,
    totalBrokers: 1,
    totalListings: 22,
    totalDeals: 89,
    rating: 4.5,
    specializations: ["Rodinné domy", "Pozemky", "Rekreační objekty"],
    parentAgencyId: "a-century21-cz",
    isIndependent: false,
  },
];

// ===== POBOČKY =====

export const branches: Branch[] = [
  {
    id: "br1",
    agencyId: "a1",
    name: "Nemovizor Prime – Praha",
    slug: "nemovizor-prime-praha",
    address: "Národní 1009/5, 110 00 Praha 1",
    city: "Praha",
    phone: "+420 800 100 200",
    email: "praha@nemovizor-prime.cz",
    latitude: 50.0815,
    longitude: 14.4165,
    isHeadquarters: true,
  },
  {
    id: "br2",
    agencyId: "a1",
    name: "Nemovizor Prime – Brno",
    slug: "nemovizor-prime-brno",
    address: "Masarykova 427/31, 602 00 Brno",
    city: "Brno",
    phone: "+420 800 100 201",
    email: "brno@nemovizor-prime.cz",
    latitude: 49.1951,
    longitude: 16.6068,
    isHeadquarters: false,
  },
  {
    id: "br3",
    agencyId: "a2",
    name: "RE/MAX Horizont – Olomouc",
    slug: "remax-horizont-olomouc",
    address: "Horní náměstí 583/7, 779 00 Olomouc",
    city: "Olomouc",
    phone: "+420 585 200 300",
    email: "olomouc@remax-horizont.cz",
    latitude: 49.5938,
    longitude: 17.2509,
    isHeadquarters: true,
  },
  {
    id: "br4",
    agencyId: "a3",
    name: "Century 21 Bonus – Plzeň",
    slug: "century-21-bonus-plzen",
    address: "Americká 2141/56, 301 00 Plzeň",
    city: "Plzeň",
    phone: "+420 377 300 400",
    email: "plzen@century21bonus.cz",
    latitude: 49.7384,
    longitude: 13.3736,
    isHeadquarters: true,
  },
  {
    id: "br5",
    agencyId: "a3",
    name: "Century 21 Bonus – České Budějovice",
    slug: "century-21-bonus-cb",
    address: "Náměstí Přemysla Otakara II. 87/25, 370 01 České Budějovice",
    city: "České Budějovice",
    phone: "+420 377 300 401",
    email: "cb@century21bonus.cz",
    latitude: 48.9745,
    longitude: 14.4742,
    isHeadquarters: false,
  },
];

// ===== MAKLÉŘI =====

export const brokers: Broker[] = [
  {
    id: "b1",
    slug: "jan-novak",
    name: "Jan Novák",
    phone: "+420 777 111 222",
    email: "jan.novak@nemovizor.cz",
    agencyId: "a1",
    agencyName: "Nemovizor Prime",
    specialization: "Rodinné domy, vily",
    activeListings: 12,
    rating: 4.9,
    totalDeals: 87,
    bio: "Specialista na prémiové nemovitosti v Praze s 15 lety zkušeností. Absolvent Vysoké školy ekonomické, obor realitní trhy. Za svou kariéru pomohl stovkám klientů najít vysněný domov. Zaměřuje se na rodinné domy a vily v pražských rezidenčních čtvrtích. Klade důraz na osobní přístup a diskrétnost.",
    languages: ["Čeština", "Angličtina", "Němčina"],
    certifications: ["Certifikovaný realitní makléř ARK ČR", "Hypoteční specialista"],
    yearStarted: 2009,
  },
  {
    id: "b2",
    slug: "tereza-svobodova",
    name: "Tereza Svobodová",
    phone: "+420 777 222 333",
    email: "tereza.svobodova@nemovizor.cz",
    agencyId: "a1",
    agencyName: "Nemovizor Prime",
    specialization: "Byty, apartmány",
    activeListings: 18,
    rating: 4.8,
    totalDeals: 124,
    bio: "Expertka na bytové jednotky a investiční nemovitosti v Brně a okolí. Více než 10 let zkušeností v realitním oboru. Pomáhá klientům s výběrem ideálního bytu, pronájmu i investiční příležitosti. Známá svou precizností při jednání a důrazem na transparentnost celého procesu.",
    languages: ["Čeština", "Angličtina"],
    certifications: ["Certifikovaný realitní makléř ARK ČR"],
    yearStarted: 2014,
  },
  {
    id: "b3",
    slug: "lucie-halova",
    name: "Lucie Hálová",
    phone: "+420 777 333 444",
    email: "lucie.halova@nemovizor.cz",
    agencyId: "a1",
    agencyName: "Nemovizor Prime",
    specialization: "Historické nemovitosti",
    activeListings: 8,
    rating: 5.0,
    totalDeals: 63,
    bio: "Specialistka na historické byty a nemovitosti v centru Prahy. Absolventka dějin umění na Karlově univerzitě. Její unikátní znalost architektury a památkové péče jí umožňuje najít skryté klenoty na trhu. Spolupracuje s předními architekty na renovacích historických objektů.",
    languages: ["Čeština", "Angličtina", "Francouzština"],
    certifications: ["Certifikovaný realitní makléř ARK ČR", "Specialista na historické objekty"],
    yearStarted: 2011,
  },
  {
    id: "b4",
    slug: "martin-vesely",
    name: "Martin Veselý",
    phone: "+420 777 444 555",
    email: "martin.vesely@nemovizor.cz",
    agencyId: "a1",
    agencyName: "Nemovizor Prime",
    specialization: "Novostavby",
    activeListings: 22,
    rating: 4.7,
    totalDeals: 156,
    bio: "Zaměřuje se na novostavby a developerské projekty po celé ČR. Díky úzkým vazbám na přední developery dokáže klientům nabídnout exkluzivní přístup k projektům ještě před jejich veřejným prodejem. Expert na energeticky úsporné stavby a chytré domácnosti.",
    languages: ["Čeština", "Angličtina"],
    certifications: ["Certifikovaný realitní makléř ARK ČR", "Energetický specialista"],
    yearStarted: 2008,
  },
  {
    id: "b5",
    slug: "petr-dolezal",
    name: "Petr Doležal",
    phone: "+420 777 555 666",
    email: "petr.dolezal@nemovizor.cz",
    agencyId: "a1",
    agencyName: "Nemovizor Prime",
    specialization: "Luxusní nemovitosti",
    activeListings: 6,
    rating: 4.9,
    totalDeals: 45,
    bio: "Luxusní segment nemovitostního trhu. České Budějovice a jižní Čechy. Petr se specializuje na exkluzivní vily a usedlosti v jihočeském kraji. Nabízí kompletní servis včetně správy nemovitostí a poradenství pro zahraniční investory.",
    languages: ["Čeština", "Angličtina", "Ruština"],
    certifications: ["Certifikovaný realitní makléř ARK ČR"],
    yearStarted: 2016,
  },
  {
    id: "b6",
    slug: "barbora-jelinkova",
    name: "Barbora Jelínková",
    phone: "+420 777 666 777",
    email: "barbora.jelinkova@nemovizor.cz",
    agencyId: "a1",
    agencyName: "Nemovizor Prime",
    specialization: "Komerční nemovitosti",
    activeListings: 15,
    rating: 4.8,
    totalDeals: 98,
    bio: "Komerční prostory, kanceláře a retail v Praze a krajských městech. Barbora má bohaté zkušenosti s transakcemi v komerčním segmentu. Poskytuje poradenství firmám při hledání ideálních prostor pro podnikání a pomáhá s vyjednáváním nájemních smluv.",
    languages: ["Čeština", "Angličtina", "Španělština"],
    certifications: ["Certifikovaný realitní makléř ARK ČR", "Komerční specialista CCIM"],
    yearStarted: 2012,
  },
  {
    id: "b7",
    slug: "tomas-krejci",
    name: "Tomáš Krejčí",
    phone: "+420 585 200 301",
    email: "tomas.krejci@remax-horizont.cz",
    agencyId: "a2",
    agencyName: "RE/MAX Horizont",
    specialization: "Rezidenční nemovitosti",
    activeListings: 19,
    rating: 4.6,
    totalDeals: 112,
    bio: "Zkušený makléř působící na Moravě s důrazem na rezidenční nemovitosti. Tomáš je rodilý Olomoučan se znalostí místního trhu, která mu umožňuje najít nejlepší příležitosti pro kupující i prodávající. Spolupracuje s mezinárodní klientelou díky zázemí RE/MAX.",
    languages: ["Čeština", "Angličtina"],
    certifications: ["RE/MAX Certified Agent"],
    yearStarted: 2013,
  },
  {
    id: "b8",
    slug: "petra-nemcova",
    name: "Petra Němcová",
    phone: "+420 585 200 302",
    email: "petra.nemcova@remax-horizont.cz",
    agencyId: "a2",
    agencyName: "RE/MAX Horizont",
    specialization: "Pronájmy, investice",
    activeListings: 15,
    rating: 4.7,
    totalDeals: 98,
    bio: "Specialistka na pronájmy a investiční nemovitosti v Olomouci a Přerově. Petra pomáhá investorům budovat portfolio nemovitostí s garantovaným výnosem. Její analytický přístup a znalost tržních dat oceňují klienti po celé Moravě.",
    languages: ["Čeština", "Angličtina", "Polština"],
    certifications: ["RE/MAX Certified Agent", "Investiční poradce"],
    yearStarted: 2016,
  },
  {
    id: "b9",
    slug: "ondrej-fiala",
    name: "Ondřej Fiala",
    phone: "+420 377 300 401",
    email: "ondrej.fiala@century21bonus.cz",
    agencyId: "a3",
    agencyName: "Century 21 Bonus",
    specialization: "Rodinné domy, pozemky",
    activeListings: 22,
    rating: 4.5,
    totalDeals: 89,
    bio: "Rodák z Plzně se zaměřením na rodinné domy a stavební pozemky v západních a jižních Čechách. Ondřej má blízký vztah k přírodě a pomáhá klientům najít ideální místo pro bydlení mimo velkoměsta. Nabízí kompletní servis od prohlídky po předání klíčů.",
    languages: ["Čeština", "Němčina"],
    certifications: ["Century 21 Certified Professional"],
    yearStarted: 2018,
  },
];

// ===== HODNOCENÍ =====

export const reviews: Review[] = [
  {
    id: "r1",
    targetType: "broker",
    targetId: "b1",
    authorName: "Michaela Procházková",
    rating: 5,
    text: "Pan Novák nám pomohl najít dokonalou vilu v Praze 6. Jeho profesionalita a znalost trhu je výjimečná. Celý proces proběhl hladce a bez komplikací.",
    date: "2025-11-15",
    propertyType: "Prodej vily 6+kk",
  },
  {
    id: "r2",
    targetType: "broker",
    targetId: "b1",
    authorName: "David Černý",
    rating: 5,
    text: "Výborná spolupráce při prodeji rodinného domu. Jan dokázal nemovitost prodat za vyšší cenu, než jsme očekávali, a to během pouhých 3 týdnů.",
    date: "2025-09-22",
    propertyType: "Prodej rodinného domu",
  },
  {
    id: "r3",
    targetType: "broker",
    targetId: "b2",
    authorName: "Kateřina Malá",
    rating: 5,
    text: "Tereza je naprosto skvělá makléřka. Pomohla nám s koupí bytu v Brně. Vždy dostupná, ochotná a profesionální. Vřele doporučuji.",
    date: "2025-12-03",
    propertyType: "Koupě bytu 3+kk",
  },
  {
    id: "r4",
    targetType: "broker",
    targetId: "b3",
    authorName: "Robert Šimek",
    rating: 5,
    text: "Lucie má neuvěřitelné znalosti historické architektury. Našla nám byt v secesním domě, o kterém jsme ani nevěděli, že je na trhu.",
    date: "2025-10-18",
    propertyType: "Koupě bytu v historickém centru",
  },
  {
    id: "r5",
    targetType: "broker",
    targetId: "b4",
    authorName: "Lenka Dvořáková",
    rating: 4,
    text: "Martin nám představil několik novostaveb, které přesně odpovídaly našim požadavkům. Oceňuji jeho technické znalosti a trpělivost.",
    date: "2025-08-30",
    propertyType: "Koupě bytu v novostavbě",
  },
  {
    id: "r6",
    targetType: "broker",
    targetId: "b7",
    authorName: "Filip Horák",
    rating: 5,
    text: "Tomáš nám pomohl s prodejem bytu v Olomouci. Rychlé jednání, férový přístup a skvělá komunikace po celou dobu spolupráce.",
    date: "2025-11-28",
    propertyType: "Prodej bytu 2+1",
  },
  {
    id: "r7",
    targetType: "agency",
    targetId: "a1",
    authorName: "Ing. Pavel Kořínek",
    rating: 5,
    text: "Nemovizor Prime je skutečně prémiová kancelář. Od prvního kontaktu po předání klíčů vše probíhalo na nejvyšší úrovni. Marketing nemovitostí je na světové úrovni.",
    date: "2025-12-10",
  },
  {
    id: "r8",
    targetType: "agency",
    targetId: "a1",
    authorName: "Jana Vlčková",
    rating: 5,
    text: "Spolupráce s Nemovizor Prime předčila naše očekávání. Profesionální fotografie, virtuální prohlídky a aktivní přístup k prezentaci naší nemovitosti.",
    date: "2025-10-05",
  },
  {
    id: "r9",
    targetType: "agency",
    targetId: "a2",
    authorName: "Martin Polák",
    rating: 4,
    text: "RE/MAX Horizont nám pomohl s pronájmem komerčního prostoru. Oceňuji mezinárodní zázemí a profesionální přístup celého týmu.",
    date: "2025-09-14",
  },
  {
    id: "r10",
    targetType: "broker",
    targetId: "b9",
    authorName: "Věra Nováčková",
    rating: 5,
    text: "Ondřej nám našel krásný pozemek u Plzně za výbornou cenu. Veškeré administrativní záležitosti vyřídil rychle a bez problémů.",
    date: "2025-11-02",
    propertyType: "Koupě stavebního pozemku",
  },
];

// ===== UTILITY FUNCTIONS =====

export function formatPrice(price: number, currency?: string) {
  const cur = (currency ?? "czk").toUpperCase();
  const localeMap: Record<string, string> = { CZK: "cs-CZ", EUR: "de-DE", GBP: "en-GB", USD: "en-US" };
  const locale = localeMap[cur] ?? "cs-CZ";
  const suffixMap: Record<string, string> = { CZK: " Kč/měs.", EUR: " \u20AC/m\u011Bs.", GBP: "/mo" };

  if (cur === "CZK" && price < 100000) {
    return new Intl.NumberFormat("cs-CZ").format(price) + " Kč/měs.";
  }
  if (cur !== "CZK" && price < 5000) {
    return new Intl.NumberFormat(locale, { style: "currency", currency: cur, maximumFractionDigits: 0 }).format(price) + (suffixMap[cur] ? "/mo" : "");
  }
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: cur,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getAllProperties(): Property[] {
  return [...properties, ...latestProperties];
}

export function filterProperties(filters: PropertyFilters): Property[] {
  return getAllProperties().filter((p) => {
    if (filters.city && p.city !== filters.city) return false;
    if (filters.category && p.category !== filters.category) return false;
    if (filters.listingType && p.listingType !== filters.listingType) return false;
    if (filters.priceMin && p.price < filters.priceMin) return false;
    if (filters.priceMax && p.price > filters.priceMax) return false;
    if (filters.areaMin && p.area < filters.areaMin) return false;
    if (filters.areaMax && p.area > filters.areaMax) return false;
    return true;
  });
}

export function getPropertyBySlug(slug: string) {
  return getAllProperties().find((p) => p.slug === slug);
}

export function getSimilarProperties(slug: string, city: string) {
  return getAllProperties()
    .filter((p) => p.slug !== slug && p.city === city)
    .slice(0, 3);
}

export function getUniqueCities() {
  return Array.from(new Set(getAllProperties().map((p) => p.city)));
}

export function getBrokerByName(name: string) {
  return brokers.find((b) => b.name === name);
}

export function getBrokerById(id: string) {
  return brokers.find((b) => b.id === id);
}

export function getBrokerBySlug(slug: string) {
  return brokers.find((b) => b.slug === slug);
}

export function getAllAgencies() {
  return agencies;
}

export function getAgencyById(id: string) {
  return agencies.find((a) => a.id === id);
}

export function getAgencyBySlug(slug: string) {
  return agencies.find((a) => a.slug === slug);
}

export function getAgencyBrokers(agencyId: string) {
  return brokers.filter((b) => b.agencyId === agencyId);
}

export function getAgencyBranches(agencyId: string) {
  return branches.filter((b) => b.agencyId === agencyId);
}

export function getBrokerReviews(brokerId: string) {
  return reviews.filter((r) => r.targetType === "broker" && r.targetId === brokerId);
}

export function getAgencyReviews(agencyId: string) {
  return reviews.filter((r) => r.targetType === "agency" && r.targetId === agencyId);
}

export function getBrokerProperties(brokerId: string) {
  return getAllProperties().filter((p) => p.brokerId === brokerId);
}

export function getAgencyProperties(agencyId: string) {
  const agencyBrokerIds = getAgencyBrokers(agencyId).map((b) => b.id);
  return getAllProperties().filter((p) => p.brokerId && agencyBrokerIds.includes(p.brokerId));
}

export function getBrokerCities(brokerId: string): string[] {
  const props = getBrokerProperties(brokerId);
  return [...new Set(props.map((p) => p.city))];
}

export function getAgencyCities(agencyId: string): string[] {
  const props = getAgencyProperties(agencyId);
  return [...new Set(props.map((p) => p.city))];
}

export function getAgencyBranchCities(agencyId: string): string[] {
  return getAgencyBranches(agencyId).map((b) => b.city);
}

export function getAllBranchCities(): string[] {
  return [...new Set(branches.map((b) => b.city))].sort();
}

export function getAllBrokerActiveCities(): string[] {
  const allCities = brokers.flatMap((b) => getBrokerCities(b.id));
  return [...new Set(allCities)].sort();
}

export function getAllSpecializations(): string[] {
  const brokerSpecs = brokers.map((b) => b.specialization);
  const agencySpecs = agencies.flatMap((a) => a.specializations);
  return [...new Set([...brokerSpecs, ...agencySpecs])].sort();
}

export function getAllLocationCities(): string[] {
  const branchCities = branches.map((b) => b.city);
  const propertyCities = [...properties, ...latestProperties].map((p) => p.city);
  return [...new Set([...branchCities, ...propertyCities])].sort();
}
